extends:
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - prettier
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
  import/resolver:
    typescript:
rules:
  no-use-before-define: 'off'
  '@typescript-eslint/indent':
    - 2
    - 2
  '@typescript-eslint/no-use-before-define':
    - 'error'
