extends:
  - airbnb
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - prettier
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
  import/resolver:
    typescript:
rules:
  import/extensions:
    - 'error'
    - ignorePackages
    - '': never
      js: never
      ts: never
  import/no-extraneous-dependencies:
    - 2
    - devDependencies:
        - '**/test/ts'
  no-use-before-define: 'off'
  '@typescript-eslint/indent':
    - 2
    - 2
  '@typescript-eslint/no-use-before-define':
    - 'error'
